### ISSUE TITLE
请确认panduan.py中在value1==value2是否存在欠妥

### ISSUE THREAD

**Issue by xiaojiu1993** [liwanlei/jiekou-python3#11]
![image](https://user-images.githubusercontent.com/35256088/60595270-3ab64a80-9dd9-11e9-87c8-555a61a04f04.png)

**Comment by liwanlei** [comment]
只对值进行判断。




| |
李雷雷
|
|
邮箱：leileili126@163.com
|

签名由 网易邮箱大师 定制

在2019年07月03日 21:26，ninenin 写道：

**Comment by ninenin** [comment]
> 只对值进行判断。 | | 李雷雷 | | 邮箱：leileili126@163.com | 签名由 网易邮箱大师 定制 在2019年07月03日 21:26，ninenin 写道： — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

您看console中的输出。在使用res方法的列表生成式中产生的结果与遍历result的key结果：['[1]', '[2]', '[3]']和['1', '2', '3']

**Comment by liwanlei** [comment]
这个地方应该是个bug，




| |
李雷雷
|
|
邮箱：leileili126@163.com
|

签名由 网易邮箱大师 定制

在2019年07月03日 21:53，ninenin 写道：

只对值进行判断。 | | 李雷雷 | | 邮箱：leileili126@163.com | 签名由 网易邮箱大师 定制 在2019年07月03日 21:26，ninenin 写道： — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

您看console中的输出。在使用res方法的列表生成式中产生的结果与遍历result的key结果：['[1]', '[2]', '[3]']和['1', '2', '3']
