### ISSUE TITLE
请确认test_requests中post方法是否有欠妥

### ISSUE THREAD

**Issue by ninenin** [liwanlei/jiekou-python3#12]
![image](https://user-images.githubusercontent.com/35256088/60595517-bdd7a080-9dd9-11e9-93dc-4422839196c8.png)
POST请求的参数中params=data是否应该是data=data?

**Comment by liwanlei** [comment]
Params就可以，我试试的没问题




| |
李雷雷
|
|
邮箱：leileili126@163.com
|

签名由 网易邮箱大师 定制

在2019年07月03日 21:31，ninenin 写道：


POST请求的参数中params=data是否应该是data=data?

**Comment by ninenin** [comment]
> Params就可以，我试试的没问题 | | 李雷雷 | | 邮箱：leileili126@163.com | 签名由 网易邮箱大师 定制 在2019年07月03日 21:31，ninenin 写道： POST请求的参数中params=data是否应该是data=data? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

请问您的params数据类型是字典吗

**Comment by liwanlei** [comment]
是。这个不是万能的，要根据你要用的项目实际去修改




| |
李雷雷
|
|
邮箱：leileili126@163.com
|

签名由 网易邮箱大师 定制

在2019年07月03日 21:59，ninenin 写道：

Params就可以，我试试的没问题 | | 李雷雷 | | 邮箱：leileili126@163.com | 签名由 网易邮箱大师 定制 在2019年07月03日 21:31，ninenin 写道： POST请求的参数中params=data是否应该是data=data? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

请问您的params数据类型是字典吗

**Comment by ninenin** [comment]
> 是。这个不是万能的，要根据你要用的项目实际去修改 | | 李雷雷 | | 邮箱：leileili126@163.com | 签名由 网易邮箱大师 定制 在2019年07月03日 21:59，ninenin 写道： Params就可以，我试试的没问题 | | 李雷雷 | | 邮箱：leileili126@163.com | 签名由 网易邮箱大师 定制 在2019年07月03日 21:31，ninenin 写道： POST请求的参数中params=data是否应该是data=data? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread. 请问您的params数据类型是字典吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

![Uploading image.png…]()
